name: Lint
on: pull_request
jobs:
  unitTest:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Create Local Properties
        run: |
          echo "MAPS_API_KEY=test" >> ./local.properties
          echo "GOOGLE_WEBCLIENT_ID=test" >> ./local.properties
      - name: Create Google Services
        run: |
          echo "${{secrets.GOOGLE_SERVICES_BASE64}}" | base64 --decode  >> ./app/google-services.json
      - run: ./gradlew lint
        name: Running Lint
      - uses: actions/upload-artifact@v4
        with:
          path: ./app/build/reports/lint-results-debug.html