name: Spotless
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  unitTest:
    name: Run spotless
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Create Local Properties
        run: |
          echo "MAPS_API_KEY=test" >> ./local.properties
          echo "GOOGLE_WEBCLIENT_ID=test" >> ./local.properties
      - name: Create Google Services
        run: |
          echo "${{secrets.GOOGLE_SERVICES_BASE64}}" | base64 --decode  >> ./app/google-services.json
      - run: ./gradlew spotlessApply
        name: Running Spotless
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Spotless fixes