name: Unit Tests
on: pull_request
jobs:
  unitTest:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run Unit Test
        run: ./gradlew test