name: Unit Test
on: pull_request
jobs:
  unitTest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Create Local Properties
        run: |
          echo "MAPS_API_KEY=test" >> ./local.properties
          echo "GOOGLE_WEBCLIENT_ID=test" >> ./local.properties
      - run: ./gradlew test
        name: Running Unit Tests